# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RType <- function(x) {
    .Call(`_introRcppManipulation_RType`, x)
}

countNAs <- function(x) {
    .Call(`_introRcppManipulation_countNAs`, x)
}

countZeroes <- function(x) {
    .Call(`_introRcppManipulation_countZeroes`, x)
}

createDF <- function() {
    .Call(`_introRcppManipulation_createDF`)
}

createList <- function() {
    .Call(`_introRcppManipulation_createList`)
}

createVec1 <- function() {
    .Call(`_introRcppManipulation_createVec1`)
}

createVec2 <- function() {
    .Call(`_introRcppManipulation_createVec2`)
}

enumerate <- function(x) {
    invisible(.Call(`_introRcppManipulation_enumerate`, x))
}

favourites <- function() {
    .Call(`_introRcppManipulation_favourites`)
}

getAlpha <- function(x) {
    .Call(`_introRcppManipulation_getAlpha`, x)
}

getLevels <- function(x) {
    .Call(`_introRcppManipulation_getLevels`, x)
}

getNonNAs <- function(x) {
    .Call(`_introRcppManipulation_getNonNAs`, x)
}

getOne <- function(x) {
    .Call(`_introRcppManipulation_getOne`, x)
}

names1 <- function(x) {
    .Call(`_introRcppManipulation_names1`, x)
}

names2 <- function(x) {
    .Call(`_introRcppManipulation_names2`, x)
}

someFactor <- function() {
    .Call(`_introRcppManipulation_someFactor`)
}

uninitialized <- function(n) {
    .Call(`_introRcppManipulation_uninitialized`, n)
}

vec0 <- function(n) {
    .Call(`_introRcppManipulation_vec0`, n)
}

vec1 <- function(n) {
    .Call(`_introRcppManipulation_vec1`, n)
}

whatever <- function(n, a) {
    .Call(`_introRcppManipulation_whatever`, n, a)
}

zeros <- function(n) {
    .Call(`_introRcppManipulation_zeros`, n)
}

