# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RType <- function(x) {
    .Call(`_manipulation_RType`, x)
}

countNAs <- function(x) {
    .Call(`_manipulation_countNAs`, x)
}

countZeroes <- function(x) {
    .Call(`_manipulation_countZeroes`, x)
}

createDF <- function() {
    .Call(`_manipulation_createDF`)
}

createList <- function() {
    .Call(`_manipulation_createList`)
}

createVec1 <- function() {
    .Call(`_manipulation_createVec1`)
}

createVec2 <- function() {
    .Call(`_manipulation_createVec2`)
}

enumerate <- function(x) {
    invisible(.Call(`_manipulation_enumerate`, x))
}

favourites <- function() {
    .Call(`_manipulation_favourites`)
}

getAlpha <- function(x) {
    .Call(`_manipulation_getAlpha`, x)
}

getLevels <- function(x) {
    .Call(`_manipulation_getLevels`, x)
}

getNonNAs <- function(x) {
    .Call(`_manipulation_getNonNAs`, x)
}

getOne <- function(x) {
    .Call(`_manipulation_getOne`, x)
}

names1 <- function(x) {
    .Call(`_manipulation_names1`, x)
}

names2 <- function(x) {
    .Call(`_manipulation_names2`, x)
}

someFactor <- function() {
    .Call(`_manipulation_someFactor`)
}

uninitialized <- function(n) {
    .Call(`_manipulation_uninitialized`, n)
}

vec0 <- function(n) {
    .Call(`_manipulation_vec0`, n)
}

vec1 <- function(n) {
    .Call(`_manipulation_vec1`, n)
}

whatever <- function(n, a) {
    .Call(`_manipulation_whatever`, n, a)
}

zeros <- function(n) {
    .Call(`_manipulation_zeros`, n)
}

